Feature/prototype
Melonps/QiiCast-Frontend pull request #1
Opened 2023-12-28 07:42 UTC by penguin-prg

## 概要
- streamlitでフロントエンドのプロトタイプを作りました
- とりあえず基本的な要素を表示できることの確認です。
- 以下の流れで動いています
  1. ウィジットからのタグ指定（デフォルトはNone） と表示件数の指定
  2. qiita apiで最近の記事を取得
  3. ratingを乱数で埋めて、ratingの上位順に表示件数の個数を表示

<img src="https://github.com/Melonps/QiiCast-Frontend/assets/66503167/cf031cee-533e-4548-a504-99e5ee3adf34" width="400">

## 動作確認
- [ ] ローカル環境でアプリが意図通り表示されることを確認した

## 確認してほしいこと/気になってること
- 初回なので、どなたか自分の環境でビルドして、アプリをブラウザで見れるとこまで確認していただきたいです。
  - apiのアクセストークン持ってる人がいいかもです。

## 補足
- ratingはひとまず乱数にしています
- 記事へのリンクがべた張りなのはまた修正します
- ディレクトリ構成はバックエンド側と調整するかもなので暫定です
- apiから落としてきたjsonファイルのフォーマットも暫定です。

2023-12-31 12:47 UTC, Melonps requested changes
動作確認できました、お疲れ様でした！
Dockerfileだけ自分の方で修正させていただきます。

2023-12-31 12:47 UTC, Melonps commented on .devcontainer/Dockerfile
以降の開発環境にガッツリ関わるので、
baseのイメージははっきり決めときますか！
今回はおそらくGPUを使わない構成になるので、以下で十分だと思います！
```
FROM python:3.10-slim
```

2023-12-31 14:30 UTC, penguin-prg commented on .devcontainer/Dockerfile
reviewありがとうございます！
探していただいたbase imageで動作することを確認してpushしました！

2024-01-03 13:56 UTC, Melonps commented
docker周りの修正確認しました！
お疲れ様です！

2024-01-03 13:57 UTC, merged